enum WALLET_TYPE {
  ETHEREUM_METAMASK,
  ETHEREUM_WALLETCONNECT,
  ALGORAND_MYALGO,
  ALGORAND_WALLETCONNECT,
  ALGORAND_PERAWALLET,
}

enum CHAIN_TYPE {
  ALGORAND,
  ETHEREUM,
}

export { WALLET_TYPE, CHAIN_TYPE };
